version: "3.3"
services:
  db:
    image: mysql:8.0  
    container_name: job-mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    restart: always
    volumes: 
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:
  node_modules:

networks:
  app-network:
    driver: bridge